# Generated by Django 5.2.8 on 2025-11-24 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question1', to='polls.question')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question2', to='polls.question')),
                ('question3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question3', to='polls.question')),
                ('question4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question4', to='polls.question')),
                ('question5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question5', to='polls.question')),
            ],
        ),
    ]
